module.exports = {
	'customer_form': import('./manager/widget/customer/form'),
	'customer_item': import('./manager/widget/customer/item'),
	'location_item': import('./manager/widget/location/item'),
	'location_view': import('./manager/widget/location/view'),
	'menu_input': import('./manager/widget/menu-input'),
	'perdrix_dock': import('./manager/dock'),
	'note_item': import('./manager/widget/note/item'),
	'note_form': import('./manager/widget/note/form'),
	'poc_item': import('./manager/widget/poc/item'),
	'poc_form': import('./manager/widget/poc/form'),
	'radio_buttons': import('./manager/widget/radio-buttons'),
	'search_results': import('./manager/widget/search-results'),
	'site_form': import('./manager/widget/site/form'),
	'site_item': import('./manager/widget/site/item'),
	'window_customer_list': import('./manager/window/customer-list'),
	'window_customer': import('./manager/window/customer'),
	'window_finder': import('./manager/window/finder'),
	'work_form': import('./manager/widget/work/form'),
	'work_item': import('./manager/widget/work/item'),
	'work_list': import('./manager/widget/work/list'),
};